package dev.giaco.springai.prompt;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

@RestController
@RequestMapping("/articles")
public class ArticleController {

    private final ChatClient chatClient;

    public ArticleController(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder.build();
    }

    @GetMapping("/posts/new")
    public String newPost(@RequestParam(value = "topic", defaultValue = "JDK Virtual Theads") String topic) {
        // What is a system message?
        // A system message is used to set the behavior of the AI assistant.
        // It helps to define the context and tone of the responses generated by the AI.
        // In this case, we want the AI to act as an expert article writer for a
        // technical blog.
        // Use it as a guide or a restriction to the model's behavior
        var system = """
                    Blog Post Generator Guidelines:

                    1. Length & Purpose: Generate 500-word blog posts that inform and engage general audiences.

                    2. Structure:
                    - Introduction: Hook readers and establish the topic's relevance
                    - Body: Develop 3 main points with supporting evidence and examples
                    - Conclusion: Summarize key takeaways and include a call-to-action

                    3. Content Requirements:
                    - Include real-world applications or case studies
                    - Incorporate relevant statistics or data points when appropriate
                    - Explain benefits/implications clearly for non-experts

                    4. Tone & Style:
                    - Write in an informative yet conversational voice
                    - Use accessible language while maintaining authority
                    - Break up text with subheadings and short paragraphs

                    5. Response Format: Deliver complete, ready-to-publish posts with a suggested title.
                """;

        return chatClient.prompt()
                .user(u -> {
                    u.text("Write me a blog post about {topic}");
                    u.param("topic", topic);
                })
                .system(system)
                .call()
                .content();

    }

}
